#!/usr/bin/env bash
# Install three thin launchers into a directory (default: $HOME):
#   start-windows.sh   -> <this clone>/scripts/start-windows.sh
#   stop-windows.sh    -> <this clone>/scripts/stop-windows.sh
#   windows-status.sh  -> <this clone>/scripts/status.sh
# The launchers contain no logic: they `exec` the repo script with "$@" (exit code is preserved).
# The clone location is detected from this script's own path at install time.
#
#   install/install-user-commands.sh [--dest DIR] [--dry-run] [--force]
#
# Without --force, an existing file that is not one of our launchers is never touched.
# With --force it is first copied to <name>.bak-<timestamp> (verified), then replaced atomically.
set -Eeuo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
DEST="${HOME:?HOME is not set}"; DRY=0; FORCE=0
MARK="# rtx-on-demand launcher"
LEGACY_MARK="# homelab-gpu-workstation launcher"   # launchers generated before the rename are ours too

while [ $# -gt 0 ]; do
  case "$1" in
    --dest) DEST="${2:?--dest needs a directory}"; shift 2 ;;
    --dry-run) DRY=1; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) sed -n '2,12p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 1 ;;
  esac
done
[ -d "$DEST" ] || { echo "destination is not a directory: $DEST" >&2; exit 1; }

is_ours() { grep -qxF -e "$MARK" -e "$LEGACY_MARK" "$1" 2>/dev/null; }

# launcher-name:repo-script
PAIRS="start-windows.sh:start-windows.sh stop-windows.sh:stop-windows.sh windows-status.sh:status.sh"

# 1. validate everything before writing anything
for p in $PAIRS; do
  [ -x "$REPO/scripts/${p#*:}" ] || { echo "missing or not executable: $REPO/scripts/${p#*:}" >&2; exit 1; }
done
for p in $PAIRS; do
  t="$DEST/${p%%:*}"
  if [ -e "$t" ] || [ -L "$t" ]; then
    if is_ours "$t"; then continue; fi   # ours: safe to refresh
    [ $FORCE = 1 ] || { echo "refusing to overwrite existing non-launcher file: $t (use --force to back it up and replace)" >&2; exit 1; }
  fi
done

# 2. install. A foreign file is copied to a timestamped backup and the copy is VERIFIED before the
#    launcher replaces it (atomic rename), so the target is never missing and never lost.
TS="$(date +%Y%m%d-%H%M%S)"
backup_foreign() { # <target>: copy, verify, print the backup path; exit on any doubt
  local t="$1" b="$1.bak-$TS"
  [ ! -e "$b" ] && [ ! -L "$b" ] || { echo "backup path already exists: $b" >&2; exit 1; }
  cp -a -- "$t" "$b" || { echo "backup failed: $t" >&2; exit 1; }
  if [ -L "$t" ]; then
    [ -L "$b" ] && [ "$(readlink -- "$t")" = "$(readlink -- "$b")" ] || { echo "backup of symlink $t could not be verified" >&2; exit 1; }
  else
    [ -f "$b" ] && cmp -s -- "$t" "$b" || { echo "backup of $t could not be verified" >&2; exit 1; }
    [ ! -s "$t" ] || [ -s "$b" ] || { echo "backup of $t is empty" >&2; exit 1; }
  fi
  echo "backed up $t to $b (verified)" >&2
}
for p in $PAIRS; do
  name="${p%%:*}"; src="$REPO/scripts/${p#*:}"; t="$DEST/$name"
  if [ $DRY = 1 ]; then
    if { [ -e "$t" ] || [ -L "$t" ]; } && ! is_ours "$t"; then echo "would back up $t then install -> $src"
    else echo "would install $t -> $src"; fi
    continue
  fi
  if { [ -e "$t" ] || [ -L "$t" ]; } && ! is_ours "$t"; then backup_foreign "$t"; fi
  tmp="$(mktemp "$DEST/.hgw-launcher.XXXXXX")"
  printf '#!/usr/bin/env bash\n%s\n# Generated by install/install-user-commands.sh. Do not edit: re-run the installer.\nexec %q "$@"\n' "$MARK" "$src" > "$tmp"
  chmod 755 "$tmp"; mv -fT -- "$tmp" "$t"
  echo "installed $t -> $src"
done
