#!/usr/bin/env bash
# Install three thin launchers into a directory (default: $HOME):
#   start-windows.sh   -> <this clone>/scripts/start-windows.sh
#   stop-windows.sh    -> <this clone>/scripts/stop-windows.sh
#   windows-status.sh  -> <this clone>/scripts/status.sh
# The launchers contain no logic: they `exec` the repo script with "$@" (exit code is preserved).
# The clone location is detected from this script's own path at install time.
#
#   install/install-user-commands.sh [--dest DIR] [--dry-run] [--force]
#
# Without --force, an existing file that is not one of our launchers is never touched.
# With --force it is first moved to <name>.bak-<timestamp> in the same directory.
set -Eeuo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
DEST="${HOME:?HOME is not set}"; DRY=0; FORCE=0
MARK="# homelab-gpu-workstation launcher"

while [ $# -gt 0 ]; do
  case "$1" in
    --dest) DEST="${2:?--dest needs a directory}"; shift 2 ;;
    --dry-run) DRY=1; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) sed -n '2,12p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 1 ;;
  esac
done
[ -d "$DEST" ] || { echo "destination is not a directory: $DEST" >&2; exit 1; }

# launcher-name:repo-script
PAIRS="start-windows.sh:start-windows.sh stop-windows.sh:stop-windows.sh windows-status.sh:status.sh"

# 1. validate everything before writing anything
for p in $PAIRS; do
  [ -x "$REPO/scripts/${p#*:}" ] || { echo "missing or not executable: $REPO/scripts/${p#*:}" >&2; exit 1; }
done
for p in $PAIRS; do
  t="$DEST/${p%%:*}"
  if [ -e "$t" ] || [ -L "$t" ]; then
    if grep -qxF "$MARK" "$t" 2>/dev/null; then continue; fi   # ours: safe to refresh
    [ $FORCE = 1 ] || { echo "refusing to overwrite existing non-launcher file: $t (use --force to back it up and replace)" >&2; exit 1; }
  fi
done

# 2. install
TS="$(date +%Y%m%d-%H%M%S)"
for p in $PAIRS; do
  name="${p%%:*}"; src="$REPO/scripts/${p#*:}"; t="$DEST/$name"
  if [ $DRY = 1 ]; then echo "would install $t -> $src"; continue; fi
  if { [ -e "$t" ] || [ -L "$t" ]; } && ! grep -qxF "$MARK" "$t" 2>/dev/null; then
    mv -- "$t" "$t.bak-$TS"; echo "backed up existing file to $t.bak-$TS"
  fi
  tmp="$(mktemp "$DEST/.hgw-launcher.XXXXXX")"
  printf '#!/usr/bin/env bash\n%s\n# Generated by install/install-user-commands.sh. Do not edit: re-run the installer.\nexec %q "$@"\n' "$MARK" "$src" > "$tmp"
  chmod 755 "$tmp"; mv -- "$tmp" "$t"
  echo "installed $t -> $src"
done
